apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-service-account
      containers:
      - name: jenkins
        image: mustakim/jenkins
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins_home/
      volumes:
        - name: jenkins
          gcePersistentDisk:
            pdName: jenkins
            fsType: ext4
